### ISSUE TITLE
win用不了？

### ISSUE THREAD

**Issue by sixgodfan** [Jedeiah/navicat_-premium_sinicization#1]
请问win用不了的么，我的没成功

**Comment by Jedeiah** [comment]
这个是Mac的汉化包，你可以尝试从官网下载对应的win版本的软件安装包（中文版），将软件包中对应的汉化包拷贝到你已经安装的软件的相应目录下。话说回来，为啥你不直接下载中文版的软件？至于破解，直接用注册机破解。

**Comment by Jedeiah** [comment]
> 请问win用不了的么，我的没成功

这个是Mac的汉化包，你可以尝试从官网下载对应的win版本的软件安装包（中文版），将软件包中对应的汉化包拷贝到你已经安装的软件的相应目录下。话说回来，为啥你不直接下载中文版的软件？至于破解，直接用注册机破解。
